extends RefCounted
class_name MapTerrainDatabase

# W = Wasser, G = Gras, S = Shore (Küste, Water Pump geht nur hier), M = Mountain (unbebaubar)
# Jede Zeile muss exakt so viele Zeichen haben wie die Grid-Breite.

const MAIN_ISLAND := [
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWSSSWWWWWWWWWWWWWWSSWWW",
	"WWWWWWWWSSSWWWWWWWWWSSWW",
	"WWWWWWWWSGGSWWWWWWWWWSWW",
	"WWWWWWWWSGGGSWWWWWWWWWWW",
	"WWWWWWWWSGGGSWWWWWWWWWWW",
	"WWWWWWWWSGGSWWWWWWWWWWWW",
	"WWWWWWWWSSSWWWWWSSWWWWWW",
	"WWWWWWWWWWWWWWWWSSWWWWWW",
	"WWSWWWWWWWWWWWWWWWWWWWWW",
	"WWSSWWWWWWWWWWWWWWWWWWWW",
	"WWWSWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
]

const SECOND_ISLAND := [
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWSSWWW",
	"WWWWWWWWWWWWWWWWWWWSSSWW",
	"WWWWWWSSSSSSSWWWWWWWWWWW",
	"WWWWSSGGGGGGGSSWWWWWWWWW",
	"WWWSGGGGGGGGGGGSWWWWWWWW",
	"WWSGGGGGGGGGGGGGSWWWWWWW",
	"WWWSGGGGGGGGGGGSWWWWWWWW",
	"WWWWSSGGGGGGGSSWWWWWWWWW",
	"WWWWWWSSSSSSSWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWSSWW",
	"WWWWWWWWWWWWWWWWWWWWSSWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
]


static func get_layout(terrain_id: String) -> Array:
	match terrain_id:
		"main":
			return MAIN_ISLAND
		"second":
			return SECOND_ISLAND
		_:
			return MAIN_ISLAND
